name: CodeCritic CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        bash setup.sh

    - name: Run Linters
      run: |
        black --check .
        mypy .
        ruff check .
        radon cc -s .

    - name: Run Tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/
